.PHONY: build install

install:
	cp qarpediem-control-center /usr/local/bin
	cp app.desktop /usr/share/applications/qarpediem-control-center.desktop 
	mkdir -p /usr/share/qarpediem-control-center
	cp app.png /usr/share/qarpediem-control-center/app.png
